name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  packages: write # for docker push
  pull-requests: write # needed to add comments
  contents: write # needed for releases
  statuses: write # for superlinter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    if: ${{ github.event_name == 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/ollama-pr.yml@main
    with:
      model: deepseek-r1
    
  # TODO: finish the readme stuff
  # update-readme:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   services:
  #     ollama:
  #       image: ollama/ollama:latest
  #       ports:
  #         - 11434:11434
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
          
  #     - name: Update Readme.md
  #       uses: Xander-Rudolph/auto-readme@main
  #       with:
  #         model: deepseek-r1
  #         working_dir: stable-diffusion
                
  scan:
    if: ${{ github.event_name == 'pull_request' }}
    name: Code scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Trivy Scan
        uses: Xander-Rudolph/trivy-scan@main
        with:
          severity: "HIGH,CRITICAL"

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.2.1 # x-release-please-version
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_OVERRIDE || secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          VALIDATE_BASH_EXEC: false # it throws warnings about the shell scripts not being executable... no idea why
          VALIDATE_ENV: false # the order it setup how it is for documentation purpose
          VALIDATE_SHELL_SHFMT: false # TODO: probably should turn this on and put it in auto fix mode...
          VALIDATE_YAML_PRETTIER: false # TODO: this one as well...

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/docker-bake.yml@main
    with:
      gitversion: "gitversion.yml"
      targets: default # searxng + sd ext
      trigger_release: ${{ github.ref_name == 'main' }}
