name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: write
  packages: write
  
jobs:
  review:
    if: ${{ github.event_name == 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/ollama-pr.yml@main
    
  trivy-scan:
    if: ${{ github.event_name == 'pull_request' }}
    name: Trivy Scan Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy Scan
        uses: Xander-Rudolph/trivy-scan@main
        with:
          severity: "HIGH,CRITICAL"

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    # uses: xander-rudolph/.github/.github/workflows/docker-publish.yml@debug
    # uses: xander-rudolph/.github/.github/workflows/docker-publish.yml@main
    uses: xander-rudolph/.github/.github/workflows/docker-bake.yml@test
    with:
      gitversion: "gitversion.yml"
      trigger_release: true
      # trigger_release: ${{ github.ref_name == 'main' }}
